tap "domt4/autoupdate"
tap "homebrew/cask"
tap "homebrew/cask-versions"

brew "n"
brew "ghq"
brew "hub"
brew "fzf"
brew "gibo"
brew "terminal-notifier"
brew "emacs"

cask "alfred"
cask "google-chrome-dev"
cask "slack-beta"
cask "visual-studio-code-insiders"
cask "1password"